#!/usr/bin/env sh
#
# Description
#   Colours for my system scripts¹.
#
# Notes
#   1: https://github.com/BeyondMagic/scripts
#
# by BeyondMagic - 2021


#--------------------------------------------------------------------------------
# Colours for lemonbar : bottom bar
#--------------------------------------------------------------------------------


# Tags : Left
             bg_tags="#14181B"
         fg_selected="#ffffff";          fg_unselect="#696969"
fg_selected_occupied="#ffffff"; fg_unselect_occupied="#82CDD2"
           layout_fg="#14181B";            layout_bg="#ffffff"

# Titles : Center
title_name_fg="#FFFFFF"; title_name_bg="#1D1D1D"
title_icon_fg="#FF5EA4"

# Memory : Right
 mem_colour="#FFFFFF";  mem_barra="#666666"; 
swap_colour="#333333"; swap_barra="#000000"; swap_icon_colour="#444444"


#--------------------------------------------------------------------------------
# Colours for lemonbar : top bar
#--------------------------------------------------------------------------------


# Clock : Left
clock_fg="#123456"; clock_bg="#ECF3FA"; clock_f_bg="#ffffff"
clock_hg="#BDCDD7"

# Sensors : Left
sensors_fg_affix="#FFFFFF"; sensors_bg_affix="#2B2B2B"
      low_low_fg="#0D2331";       low_low_bg="#87C7E4"
      nor_low_fg="#0D2331";       nor_low_bg="#BDCDD7"
      med_med_fg="#340010";       med_med_bg="#FAFBC2"
      hig_med_fg="#0D2331";       hig_med_bg="#FF4464"

# Song : Center
       background_before="#2b2b2b"
         background_icon="#000000"
    background_song_name="#000000"
 first_running_song_name="#3E94D2"
second_running_song_name="#E4F2FF"
    background_icon_name="#FFFFFF"
            neighbors_fg="#666666"

# Tasks : Right
     task_fg="#F8FFF8"
task_fg_icon="#243F76"

# Power Button : Right
    power_fg="#FaFaFa"; power_bg="#C92430"
power_before="#000000"


#--------------------------------------------------------------------------------
# String for lemonbar : top bar
#--------------------------------------------------------------------------------


       icon_affix=""
      icon_paused=""
     icon_running=""
extra_icon_paused=": •́ ◇ •̀ : "


#--------------------------------------------------------------------------------
# Numbers for lemonbar : top bar
#--------------------------------------------------------------------------------


limit_extra_length=35
        song_limit=20
