return {
	LazyButton = 'TabLine',
	LazyButtonActive = 'TabLineSel',
	LazyCommit = 'Number',
	LazyCommitIssue = 'LazyUrl',
	LazyCommitType = 'Type',
	LazyDir = 'Directory',
	LazyH1 = 'markdownH1',
	LazyH2 = 'markdownH2',
	LazyProp = '@field',
	LazyReasonEvent = 'Repeat',
	LazyReasonFt = 'Conditional',
	LazyReasonImport = 'Function',
	LazyReasonKeys = 'String',
	LazyReasonPlugin = 'Label',
	LazyReasonSource = 'Include',
	LazyReasonStart = 'Constant',
	LazySpecial = 'Special',
	LazyTaskOutput = 'Statement',
	LazyUrl = 'Underlined',
}
