return {
	--CmpItemAbbrMatchFuzzy = { fg = COLOUR.fg_0, nocombine = true, underline = true},
	--CmpItemAbbrMatch         = 'Underlined',
	--CmpItemAbbr              = 'Ignore',
	CmpItemKind              = { fg = COLOUR.bg_1, bg = COLOUR.blue_3 },
	--CmpItemKindClass         = 'CmpItemKindStruct',
	CmpItemKindsp            = 'Label',
	--CmpItemKindConstant      = 'Constant',
	--CmpItemKindConstructor   = 'CmpItemKindMethod',
	--CmpItemKindEnum          = 'CmpItemKindStruct',
	--CmpItemKindEnumMember    = 'CmpItemKindConstant',
	--CmpItemKindEvent         = 'Repeat',
	--CmpItemKindField         = 'Identifier',
	--CmpItemKindFile          = 'Directory',
	--CmpItemKindFolder        = 'CmpItemKindFile',
	--CmpItemKindFunction      = 'Function',
	--CmpItemKindInterface     = 'Type',
	--CmpItemKindKeyword       = 'Keyword',
	--CmpItemKindMethod        = 'CmpItemKindFunction',
	--CmpItemKindModule        = 'Include',
	--CmpItemKindOperator      = 'Operator',
	--CmpItemKindProperty      = 'CmpItemKindField',
	--CmpItemKindReference     = 'StorageClass',
	--CmpItemKindSnippet       = 'Special',
	--CmpItemKindStruct        = 'Structure',
	--CmpItemKindText          = 'String',
	--CmpItemKindTypeParameter = 'Typedef',
	--CmpItemKindUnit          = 'CmpItemKindStruct',
	--CmpItemKindValue         = 'CmpItemKindConstant',
	--CmpItemKindVariable      = { fg = COLOUR.bg_1, bg = COLOUR.fg_0 },

  CmpItemAbbr               = { fg = COLOUR.fg_2, bg = NONE },
  CmpItemAbbrMatch          = { fg = COLOUR.red_1, bg = NONE, bold = true},
  CmpItemAbbrMatchFuzzy     = { fg = COLOUR.red_0, bg = NONE, bold = true},
  CmpItemMenu               = { fg = COLOUR.fg_5, bg = NONE, italic = true},
  CmpItemKindInterface      = { fg = COLOUR.bg_1, bg = COLOUR.green_0 },
  CmpItemKindColor          = { fg = COLOUR.bg_1, bg = COLOUR.violet_0 },
  CmpItemKindTypeParameter  = { fg = COLOUR.bg_1, bg = COLOUR.green_0 },
  CmpItemKindText           = { fg = COLOUR.bg_1, bg = COLOUR.orange_0 },
  CmpItemKindEnum           = { fg = COLOUR.bg_1, bg = COLOUR.blue_1 },
  CmpItemKindKeyword        = { fg = COLOUR.bg_1, bg = COLOUR.yellow_0 },
  CmpItemKindConstant       = { fg = COLOUR.bg_1, bg = COLOUR.red_0 },
  CmpItemKindConstructor    = { fg = COLOUR.bg_1, bg = COLOUR.yellow_0 },
  CmpItemKindReference      = { fg = COLOUR.bg_1, bg = COLOUR.blue_1 },
  CmpItemKindFunction       = { fg = COLOUR.bg_1, bg = COLOUR.orange_0 },
  CmpItemKindStruct         = { fg = COLOUR.bg_1, bg = COLOUR.green_0 },
  CmpItemKindClass          = { fg = COLOUR.bg_1, bg = COLOUR.violet_0 },
  CmpItemKindModule         = { fg = COLOUR.bg_1, bg = COLOUR.blue_3},
  CmpItemKindOperator       = { fg = COLOUR.bg_1, bg = COLOUR.violet_0},
  CmpItemKindField          = { fg = COLOUR.bg_1, bg = COLOUR.green_0},
  CmpItemKindProperty       = { fg = COLOUR.bg_1, bg = COLOUR.orange_0},
  CmpItemKindEvent          = { fg = COLOUR.bg_1, bg = COLOUR.blue_1},
  CmpItemKindUnit           = { fg = COLOUR.bg_1, bg = COLOUR.yellow_0},
  CmpItemKindSnippet        = { fg = COLOUR.bg_1, bg = COLOUR.red_0 },
  CmpItemKindFolder         = { fg = COLOUR.bg_1, bg = COLOUR.yellow_0 },
  CmpItemKindVariable       = { fg = COLOUR.bg_1, bg = COLOUR.blue_1 },
  CmpItemKindFile           = { fg = COLOUR.bg_1, bg = COLOUR.orange_0 },
  CmpItemKindMethod         = { fg = COLOUR.bg_1, bg = COLOUR.green_0 },
  CmpItemKindValue          = { fg = COLOUR.bg_1, bg = COLOUR.violet_0 },
  CmpItemKindEnumMember     = { fg = COLOUR.bg_1, bg = COLOUR.blue_3 },
}
