#!/usr/bin/env sh
#
# Run login manager.
#
# João Farias © 2024 BeyondMagic <beyondmagic@mail.ru>

set -e
sv check elogind >/dev/null || exit 1
sleep 1
mkdir -p /var/lib/sddm
chown -R sddm:sddm /var/lib/sddm
exec sddm 2>&1
