#!/usr/bin/env zsh

function title {
#  if [[ "$TERM" == "screen" ]]; then 

#    echo -en "\ek$1\e\\" #set screen hardstatus, usually truncated at 20 chars

		case "$(echo "$1" | head -n1 | awk '{print $1}')" in
			printf | print | echo | ls) return
		esac
		
    print -Pn "\e[5 q\e]2;$2\a\e]1;$1\a" #set window name
			# (will override window name on broken terminal)

}

ZSH_THEME_TERM_TAB_TITLE_IDLE="%15<..<%~%<<" #15 char left truncated PWD
ZSH_THEME_TERM_TITLE_IDLE="%n@%m: %~"

#Appears when you have the prompt
function precmd {

  title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE

}

#Appears at the beginning of (and during) of command execution
function preexec {

#	echo "$cmd"

  local -a cmd; cmd=(${(z)1}) # the command string

  title "$cmd" "%100>...>$2%<<"


}
