#!/usr/bin/env sh
#
# DESCRIPTION:
#   Execute magic's desktop :)
#
# Executed by startx (run your window manager from here)

#-------------------------------------------------------------------------------
# Environment Variables
#-------------------------------------------------------------------------------

export NO_AT_BRIDGE=1 \
       NOTMUCH_CONFIG="$HOME/.config/nt/" \
       PASSWORD_STORE_DIR="$HOME/.config/nt" \
       XMODIFIERS='@im=fcitx5' \
       GTK_IM_MODULE='fcitx5' \
       QT_IM_MODULE='fcitx5' \
       ZDOTDIR="$HOME/.config/zsh/" \
       LESSHISTFILE='/dev/null' \
       XDG_CONFIG_HOME="$HOME/.config/" \
       XMODIFIERS="@im=fcitx5" \
       EDITOR="nvim" "VISUAL=nvim" \
       BROWSER='vieb' \
       GNUPGHOME="$HOME/.config/gnupg" \
       CARGO_HOME="$HOME/.config/cargo" \
       READER='zathura' \
       FILE='nnn' \
       GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0" \
       ZDOTDIR="$HOME/.config/zsh" \
       LESSHISTFILE='/dev/null' \
       XDG_CONFIG_HOME="$HOME/.config/" \
       XCURSOR_THEME='Breeze-Snow (left)' \
       PATH="$HOME/.config/.cargo/bin:$HOME/github/scripts/fetch:$HOME/.local/bin:$HOME/github/scripts/root:$HOME/github/scripts/system:$HOME/github/scripts/screenshot:$HOME/github/scripts/colour:$HOME/github/scripts/quotes:$PATH"



#-------------------------------------------------------------------------------
# Start shit
#-------------------------------------------------------------------------------

#   Choose wallpaper with FEH
feh --no-fehbg --bg-scale "$(fcat desktop/wallpapers_history | tail -n1)" &

#   Start xbindkeys for keybinds
xbindkeys -f "$HOME/desktop/xbindkeysrc" &

#   Start MPD and MPD Scrible to Lastfm and Music
mpd "$HOME/.config/mpd/mpd.conf" &
mpdscribble --conf "$HOME/.config/mpdscribble/mpdscribble.conf" &

#   Picom as compositor
picom &

#   Start downloading some music :)
zsh -c '. ~/desktop/aliasesrc; mdemonde' &

#   Japanese Keyboard
fcitx5 &

#   Start Pulseaudio for sound
pulseaudio &

#   Start unclutter to make mouse disappear after one second
unclutter --timeout 1 &

#   Start Lemonbar (bottom and top bars)
$HOME/github/scripts/bars/start_bars &

#   Set Keyboard to Portuguese ABNT 2
setxkbmap -model abnt2 -layout br -variant abnt2 &

#   Set Keyboard speed typing
xset r rate 170 60 & 

#   Set Mouse speed
xinput --set-prop 11 277 0.5 &

#   Set Left Handed Mouse
xmodmap -e 'pointer = 3 2 1' &

#   Remove shit
rm -rf \
  "$HOME/.zlogin" \
  "$HOME/.xsession-errors" \
  "$HOME/.xsession" \
  "$HOME/.lyrics" &

#   Lock screen because yes
eval "sleep 8; lock" & 

#   Sleep after 12 minutes of inactivity
xautolock -time 5 -locker "lock" &

#   Reset xbindkeys ??? a few keybinds only work with this
#killall xbindkeys; xbindkeys -f "$HOME/desktop/xbindkeysrc" &

#   Start SSH-AGENT
ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null

#   Start Window Manager
exec dwm

