#!/usr/bin/env sh
#
# DESCRIPTION:
#   Execute magic's desktop :)
#
# MAINTAINER: (s)
#   BeyondMagic © 2021-

#-------------------------------------------------------------------------------
# Environment Variables
#-------------------------------------------------------------------------------

export NO_AT_BRIDGE=1 \
       LIMIT_WALLPAPERS=50 \
       TRASH="$HOME/.local/trash" \
       XWALLPAPERS_FOLDER="$HOME/Images/wallpapers" \
       XWALLPAPER_HISTORY="$HOME/.cache/xwallpapers_history" \
       XNOTIFY_FIFO="$HOME/.cache/xnotify.fifo" \
       NOTMUCH_CONFIG="$HOME/.config/nt/" \
       PASSWORD_STORE_DIR="$HOME/.config/nt" \
       PARU_CONF="$HOME/.config/paru/paru.conf" \
       XDG_CONFIG_HOME="$HOME/.config/" \
       EDITOR="nvim" "VISUAL=nvim" \
       BROWSER='firefox' \
       XDG_CONFIG_HOME="$HOME/.config" \
       GNUPGHOME="${XDG_CONFIG_HOME}/gnupg" \
       CARGO_HOME="${XDG_CONFIG_HOME}/cargo" \
       SCRIPTS_FOLDER="${HOME}/git/scripts" \
       READER='zathura' \
       BARS_TOP_FIFO='/tmp/top.fifo' \
       BARS_BOTTOM_FIFO='/tmp/bottom.fifo' \
       FILE='nnn' \
       EDITOR='nvim' \
       VISUAL='nvim' \
       GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0" \
       ZDOTDIR="$HOME/.config/zsh" \
       LESSHISTFILE='/dev/null' \
       PATH="$HOME/.config/.cargo/bin:$HOME/git/scripts/colour:$HOME/git/scripts/mpd:$HOME/git/scripts/quotes:$HOME/git/scripts/root:$HOME/git/scripts/screenshot:$HOME/.local/bin:$PATH"


#-------------------------------------------------------------------------------
# Start shit (Important session)
#-------------------------------------------------------------------------------

#   Just get colours
xrdb ~/.config/xorg/XResources

#   Input method
fcitx5 & disown

#   Start keyboard manager
dwm &

# Pokit agent
polkit-dumb-agent &

#   Start Lemonbar (bottom and top bars)
"$SCRIPTS_FOLDER"/bars/lemonbars &

# Choose wallpaper with FEH
xwallpaper --stretch "$(tail -n1 "$XWALLPAPER_HISTORY")" &

# Picom as compositor
picom --experimental-backends --blur-method dual_kawase --blur-strength 3 --animations --animation-for-open-window 'zoom' --animation-stiffness 500 --animation-dampening 25 &

#-------------------------------------------------------------------------------
# Start shit (Not so important session)
#-------------------------------------------------------------------------------

#  Load a new null module to set when recording
pactl load-module module-null-sink sink_name=null

#  Notifications per tag change
xnotify -o 0<>"$XNOTIFY_FIFO" &

#   Start xbindkeys for keybinds
xbindkeys -f "$HOME/Base/xbindkeysrc" &

#   Start MPD and MPD Scrible to Lastfm and Music
mpd "$HOME/.config/mpd/mpd.conf" &
mpdscribble --conf "$HOME/.config/mpdscribble/mpdscribble.conf" &

#   Set Keyboard speed typing
xset r rate 170 60 & 

#   Set Mouse speed
xinput --set-prop 12 310 -0.75 &

#   Set Left Handed Mouse
xmodmap -e 'pointer = 3 2 1' &

#   Start unclutter to make mouse disappear after one second
unclutter --timeout 1 &

#   Open new terminal and todoncli7
st -g '76x30+830+57' -t 'todoncli' -e 'dash' '-c' 'cd ~/git/tdtd && node todoncli.js' &

#   Notification server
dunst -s -follow keyboard &

#   Start modules for lemonbars (bottom and top bars)
"$SCRIPTS_FOLDER"/bars/modules &

#   Set cursor
gsettings set org.gnome.desktop.interface cursor-theme "$(xgetres Xcursor.theme)"

#   Start SSH-AGENT and dbus
eval $(ssh-agent) &
export $(dbus-launch) &

#   Set keyboard to ABNT2 PT-BR
setxkbmap -model abnt2 -layout br -variant abnt2 &

#   Sleep after 7 minutes of inactivity
xautolock -time 7 -locker "lock"
