#!/usr/bin/env dash
#
# João Farias © BeyondMagic 2023 <beyondmagic@mail.ru>

# In this file, set LANG and LC_ALL to en_US.UTF-8 on non-English systems to avoid mystery crashes.
. /etc/conf.d/plexmediaserver

# Depends on dbus running.
#sv check dbus > /dev/null || exit 1

exec "/usr/lib/plexmediaserver/Plex Media Server" #> /dev/null 2>&1
