return {
	coqConstructor = 'Constant',
	coqDefBinderType = 'coqDefType',
	coqDefContents1 = 'coqConstructor',
	coqDefType = 'Typedef',
	coqIndBinderTerm = 'coqDefBinderType',
	coqIndConstructor = 'Delimiter',
	coqIndTerm = 'Type',
	coqKwd = 'Keyword',
	coqKwdParen = 'Function',
	coqProofDelim = 'coqVernacCmd',
	coqProofDot = 'coqTermPunctuation',
	coqProofPunctuation = 'coqTermPunctuation',
	coqRequire = 'Include',
	coqTactic = 'Operator',
	coqTermPunctuation = 'Delimiter',
	coqVernacCmd = 'Statement',
	coqVernacPunctuation = 'coqTermPunctuation',
}
