return {
	cssAtRule = 'PreCondit',
	cssAttr = 'Keyword',
	cssAttrComma = 'Noise',
	cssAttrRegion = 'Keyword',
	cssBraces = 'Delimiter',
	cssClassName = 'Identifier',
	cssClassNameDot = 'Noise',
	cssFlexibleBoxAttr = 'cssAttr',
	cssFunctionComma = 'Noise',
	cssImportant = 'Exception',
	cssNoise = 'Noise',
	cssProp = 'Label',
	cssPseudoClass = 'Special',
	cssPseudoClassId = 'cssSelectorOp',
	cssSelectorOp = 'Operator',
	cssTagName = 'Structure',
	cssUnitDecorators = 'Type',
}
