return {
	goBlock = 'Delimiter',
	goBoolean = 'Boolean',
	goBuiltins = 'Function',
	goField = 'Identifier',
	goFloat = 'Float',
	goFormatSpecifier = 'Character',
	goFunction = 'Function',
	goFunctionCall = 'goFunction',
	goFunctionReturn = {},
	goImport = 'Include',
	goMethodCall = 'goFunctionCall',
	goPackage = 'goStatement',
	goParamType = 'goReceiverType',
	goPointerOperator = 'StorageClass',
	goPredefinedIdentifiers = 'Constant',
	goReceiver = 'goBlock',
	goReceiverType = 'goTypeName',
	goSimpleParams = 'goBlock',
	goStatement = 'Keyword',
	goType = 'Type',
	goTypeConstructor = 'goFunction',
	goTypeName = 'Type',
	goVarAssign = 'Identifier',
	goVarDefs = 'goVarAssign',
}
