return {
	markdownCode = 'mkdCode',
	markdownCodeDelimiter = 'mkdCodeDelimiter',
	markdownEscape = 'SpecialChar',
	markdownH1 = {fg = COLOUR.red_3, bold = true},
	markdownH2 = {fg = COLOUR.orange_0, bold = true},
	markdownH3 = {fg = COLOUR.yellow_0, bold = true},
	markdownH4 = {fg = COLOUR.green_5, bold = true},
	markdownH5 = {fg = COLOUR.blue_3, bold = true},
	markdownH6 = {fg = COLOUR.fg_4, bold = true},
	markdownLinkDelimiter = 'mkdDelimiter',
	markdownLinkText = 'mkdLink',
	markdownLinkTextDelimiter = 'markdownLinkDelimiter',
	markdownUrl = 'mkdURL',
	mkdBold = 'Ignore',
	mkdBoldItalic = 'mkdBold',
	mkdCode = 'Statement',
	mkdCodeDelimiter = 'mkdBold',
	mkdCodeEnd = 'mkdCodeStart',
	mkdCodeStart = 'mkdCodeDelimiter',
	mkdDelimiter = 'Delimiter',
	mkdHeading = 'Delimiter',
	mkdItalic = 'mkdBold',
	mkdLineBreak = 'NonText',
	mkdLink = 'Underlined',
	mkdListItem = 'Special',
	mkdRule = function(self) return {fg = COLOUR.fg_3, sp = COLOUR.fg_1, underline = true} end,
	mkdURL = 'htmlString',
}
