return {
	pythonBrackets = 'Delimiter',
	pythonBuiltinFunc = 'Operator',
	pythonBuiltinObj = 'Type',
	pythonBuiltinType = 'Type',
	pythonClass = 'Structure',
	pythonClassParameters = 'pythonParameters',
	pythonDecorator = 'PreProc',
	pythonDottedName = 'Identifier',
	pythonError = 'Error',
	pythonException = 'Exception',
	pythonInclude = 'Include',
	pythonIndentError = 'pythonError',
	pythonLambdaExpr = 'pythonOperator',
	pythonOperator = 'Operator',
	pythonParam = 'Identifier',
	pythonParameters = 'Delimiter',
	pythonSelf = 'Statement',
	pythonSpaceError = 'pythonError',
	pythonStatement = 'Statement',
}
