return {
	['@lsp.mod.callable.rust'] = '@lsp.type.function',
	['@lsp.type.builtinType.rust'] = '@lsp.type.type',
	['@lsp.type.character.rust'] = {},
	['@lsp.type.decorator.rust'] = '@preproc',
	['@lsp.type.derive.rust'] = '@macro',
	['@lsp.type.enumMember.rust'] = {},
	['@lsp.type.macro.rust'] = {},
	['@lsp.type.operator.rust'] = {},
	['@lsp.type.selfKeyword.rust'] = '@keyword',
	['@lsp.type.selfTypeKeyword.rust'] = '@lsp.type.typeAlias.rust',
	['@lsp.type.string.rust'] = {},
	['@lsp.type.typeAlias.rust'] = '@type.definition',
	['@lsp.typemod.character.injected.rust'] = '@lsp.type.character',
	['@lsp.typemod.deriveHelper.attribute.rust'] = '@lsp.type.decorator.rust',
	['@lsp.typemod.keyword.injected.rust'] = '@keyword',
	['@lsp.typemod.macro.injected.rust'] = '@macro',
	['@lsp.typemod.operator.injected.rust'] = '@operator',
	['@lsp.typemod.string.injected.rust'] = '@lsp.type.string',
	rustAssert = 'Debug',
	rustCharacterDelimiter = 'rustNoise',
	rustIdentifier = 'Identifier',
	rustStaticLifetime = 'rustStorage',
	rustStringDelimiter = 'rustNoise',
}
