#!/usr/bin/env dash
#
# João Farias © BeyondMagic 2023 <beyondmagic@mail.ru>

# Depends on dbus running.
#sv check dbus > /dev/null || exit 1

export LOG_LEVEL=info
export CAPTCHA_SOLVER=none

exec /usr/bin/python /opt/flaresolverr/flaresolverr.py #> /dev/null 2>&1
