#!/usr/bin/env dash
#
# João Farias © BeyondMagic 2023 <beyondmagic@mail.ru>

# Depends on dbus running.
#sv check dbus > /dev/null || exit 1

exec /usr/bin/python /usr/lib/bazarr/bazarr.py --no-update --config /var/lib/bazarr #> /dev/null 2>&1
