#!/usr/bin/env sh

#
# Recontrol
#

map <C-i> recolor

#
# Automatic color theme
#

set adjust-open width       "width"
set recolor true            "true"
set window-title-basename   "true"
set selection-clipboard     "clipboard"
set render-loading          "true"
set notification-error-bg   "#ff5555" # Red
set notification-error-fg   "#f8f8f2" # Foreground
set notification-warning-bg "#ffb86c" # Orange
set notification-warning-fg "#171919" # Selection
set notification-bg         "#141617" # Background
set notification-fg         "#f8f8f2" # Foreground
set completion-bg           "#0c0c0f" # Background
set completion-fg           "#6272a4" # Comment
set completion-group-bg     "#141617" # Background
set completion-group-fg     "#6272a4" # Comment
set completion-highlight-bg "#171919" # Selection
set completion-highlight-fg "#f8f8f2" # Foreground
set index-bg                "#0c0c0f"  # Background
set index-fg                "#f8f8f2" # Foreground
set index-active-bg         "#171919" # Current Line
set index-active-fg         "#f8f8f2" # Foreground
set inputbar-bg             "#0c0c0f" # Background
set inputbar-fg             "#f8f8f2" # Foreground
set statusbar-bg            "#141617" # Background
set statusbar-fg            "#f8f8f2" # Foreground
set highlight-color         "#f0ff44" # Orange
set highlight-active-color  "#62ff44" # Pink
set default-bg              "#0c0c0c" # Background
set default-fg              "#f8f8f2" # Foreground
set render-loading-fg       "#f8f8f2" # Background
set render-loading-bg       "#0c0c0f" # Foreground
set recolor-lightcolor      "#ff00ff" # Background
set recolor-darkcolor       "#f8f8f2" # Foreground
