dmenu.background       : #ffffff
dmenu.foreground       : #000000
dmenu.sel_background   : #111111
dmenu.sel_foreground   : #ffefc4
dmenu.out_background   : #111111
dmenu.out_foreground   : #bd9150
dmenu.selhi_background : #ffffff
dmenu.selhi_foreground : #f7497e
dmenu.hi_background    : #eeeeee
dmenu.hi_foreground    : #bb292c
