#!/usr/bin/env sh

[global]
  font = Noto Sans CJK JP 10
  geometry = "400x40-55+70"
  indicate_hidden = yes
  shrink = no
  transparency = 0
  notification_height = 0
  separator_height = 2
  padding = 10
  horizontal_padding = 10
  frame_width = 2
  frame_color = "#x"
  separator_color = frame
  sort = yes
  idle_threshold = 120
  line_height = 0
  markup = full
  format = "<span><b>%s %p</b></span>\n%b"
  alignment = center
  show_age_threshold = 60
  word_wrap = yes
  ellipsize = middle
  ignore_newline = no
  stack_duplicates = true
  hide_duplicate_count = false
  show_indicators = yes
  icon_position = left
  max_icon_size = 64
  icon_path = /usr/share/icons/BeautyLine/actions:/usr/share/icons/BeautyLine/places/16:/usr/share/icons/BeautyLine/devices/:/usr/share/icons/BeautyLine/apps
  sticky_history = yes
  history_length = 20
  always_run_script = true
  startup_notification = false
  verbosity = mesg
  corner_radius = 0
  force_xinerama = false
  mouse_left_click = close_current
  mouse_middle_click = do_action
  mouse_right_click = close_all
  content_alignment = center


[shortcuts]
  close = ctrl+shift+space
#  close_all = ctrl+shift+space
  context = ctrl+shift+period

[urgency_low]
  background = "#ffffff" # BACKGROUND_LOW
  foreground = "#444444" # FOREGROUND_LOW
  frame_color = "#A2C0CB" # FRAMECOLOR_LOW
  timeout = 5

[urgency_normal]
  background = "#F8F6FE" # BACKGROUND_NORMAL
  foreground = "#333333" # FOREGROUND_NORMAL
  frame_color = "#9E9E9E" # FRAMECOLOR_NORMAL
  timeout = 10

[urgency_critical]
  background = "#F8F6FE" # BACKGROUND_CRITICAL
  foreground = "#Fe2d3b" # FOREGROUND_CRITICAL
  frame_color = "#010000" # FRAMECOLOR_CRITICAL
  timeout = 0
  icon = /usr/share/icons/Paper/16x16/status/dialog-warning.png
