#!/usr/bin/env dash
#
# João Farias © 2024 BeyondMagic <beyondmagic@mail.ru>

export DIST='/mnt/armazenamento/.compartilhado/projetos/usando/chartdb/dist'

cd $DIST

exec python3 -m http.server 1234 -b 0.0.0.0
