#!/usr/bin/env sh

[global]

  # Position the notification in the top right corner
  origin = top-right

  # Scale factor. It is auto-detected if value is 0.
  scale = 0

  # Maximum number of notification (0 means no limit)
  notification_limit = 0
  indicate_hidden = yes
  shrink = no
  transparency = 0
  separator_color = "#13171a66"
  sort = yes
  idle_threshold = 120
  line_height = 0
  markup = full
  format = "<span><b>%s %p</b></span>\n%b"
  alignment = center
  show_age_threshold = 60
  word_wrap = yes
  ellipsize = middle
  ignore_newline = no
  stack_duplicates = true
  hide_duplicate_count = false
  show_indicators = yes
  icon_position = left
  sticky_history = yes
  history_length = 20
  always_run_script = true
  corner_radius = 0
  force_xinerama = false
  mouse_left_click = close_current
  mouse_middle_click = do_action, close_current
  mouse_right_click = close_all

  font = Noto Sans CJK JP 10
  width = 300
  height = 80
  offset = 45x60
  separator_height = 2
  padding = 10
  horizontal_padding = 10
  frame_width = 0
  max_icon_size = 64

[urgency_low]
  background = "#000000AA"
  foreground = "#A8A8A8"
  frame_color = "#111111"
  timeout = 5

[urgency_normal]
  background = "#13171aAA"
  foreground = "#ffffff"
  frame_color = "#000000"
  timeout = 10

[urgency_critical]
  background = "#13171aAA"
  foreground = "#D39B8D"
  frame_color = "#141e24"
  timeout = 0
