[settings]
max_title_length = 75
icon_size = 22

[settings.windows.screen_corner]
size = 25

[settings.background]
# Set values in the range of 0 to 1 (mathematically: [0, 1]).
red = 0
green = 0
blue = 0
alpha = 1

# Default workspaces to be always shown.
# The names can be changed by renaming with Hyprland setter (hyprctl).
# This until https://github.com/hyprwm/Hyprland/issues/4492 is closed.
#
# Special workspaces (with ids below 0) can also be rendered as a icon.
# But only when setting data.toml and dividing by an space character.
[[settings.workspaces]]
id = 1
name = "一"

[[settings.workspaces]]
id = 2
name = "二"

[[settings.workspaces]]
id = 3
name = "三"

[[settings.workspaces]]
id = 4
name = "四"

[[settings.workspaces]]
id = 5
name = "五"

[[settings.workspaces]]
id = 6
name = "六"

[[settings.workspaces]]
id = 7
name = "七"

[[settings.workspaces]]
id = 8
name = "八"

[[settings.workspaces]]
id = 9
name = "九"

[[settings.workspaces]]
id = 10
name = "十"

[[settings.workspaces]]
id = -98
# The `love-heart` is the icon, which will be rendered with `-symbolic` with GTK.
# And `magic` is the name of the special workspace (to be able to toggle by pressing the button).
name = "love-heart scratchpad"

# This section determines how the classes of windows
# are viewed i
# Terminal such as foot.
[[common]]
find = ["foot"]
replace = "command-terminal"

# Android related tools.
[[common]]
find = ["blueman-manager"]
replace = "tool-bluetooth-any"

# Android related tools.
[[common]]
find = ["io.github.whoozle.android-file-transfer"]
replace = "tool-android-any"

# Browser such as Firefox.
[[common]]
find = ["firefox-nightly", "Brave-browser", "Google-chrome"]
replace = "internet-browser"

# Image viewer such as swayimg.
[[common]]
find = ["swayimg"]
replace = "any-image-viewer"

# Social media applications such as Telegram, Mastodon, ...
[[common]]
find = ["org.telegram.desktop", "vesktop", "Beeper", "BeeperTexts"]
replace = "social-media"

# Streaming applications such as Stremio.
[[common]]
find = ["com.stremio.stremio"]
replace = "movie-streaming"

# Email applications such as Thunderbird.
[[common]]
find = ["thunderbird", "org.gnome.Evolution"]
replace = "email-manager"

# Screen-shoting applications such as Flameshot.
[[common]]
find = ["flameshot"]
replace = "tool-screenshot"

# Note-taking applications such as Obsidian.
[[common]]
find = ["obsidian"]
replace = "tool-notetaking"

# Design applications such as Inkscape.
[[common]]
find = ["org.inkscape.Inkscape"]
replace = "tool-designer"

# Video viewer applications such as mpv.
[[common]]
find = ["mpv"]
replace = "any-video-viewer"

# Video editor applications such as Olive.
[[common]]
find = ["org.olivevideoeditor.Olive"]
replace = "video-plus"

# Android applications such as waydroid.
[[common]]
find = ["Waydroid"]
replace = "android"

# Game applications such as Steam.
[[common]]
find = ["steam"]
replace = "game"

# Code editor applications such as Visual Studio Code.
[[common]]
find = ["Code", "code"]
replace = "code-editor"

# Digital art tool such as Gimp, Krita...
[[common]]
find = ["krita", "Gimp", "Gimp-2.10"]
replace = "digital-art-tool"

# For note-taing tools such as Rnote.
[[common]]
find = ["com.github.flxzt.rnote", "rnote"]
replace = "tool-note-taking"

# File manager/explorers such as Thunar, xdg-desktop-open-portal, ...
[[common]]
find = ["xdg-desktop-portal-gtk"]
replace = "tool-file-explorer"

# Any downloader tool such as qBittorrent.
[[common]]
find = ["org.qbittorrent.qBittorrent"]
replace = "tool-any-downloader"

# Book reader..
[[common]]
find = ["org.pwmt.zathura", "com.github.johnfactotum.Foliate", "sioyek"]
replace = "any-book-reader"

# Constant repetitive learning.
[[common]]
find = ["anki"]
replace = "any-flashcard-learning-tool"

# Japanese learning resource.
[[common]]
find = ["dakanji"]
replace = "japanese-character"

# Input method application (to set keyboard of different languages).
[[common]]
find = ["org.fcitx.fcitx5-config-qt"]
replace = "input-method-set"

# Sound and music..
[[common]]
find = ["pavucontrol", "songrec", "org.pulseaudio.pavucontrol"]
replace = "sound-loud"

# Message servies overall..
[[common]]
find = ["Ferdium", "ferdium"]
replace = "message-service"

# Message servies overall..
[[common]]
find = ["PacketTracer"]
replace = "network-wired-logical"
