#!/usr/bin/env bash

artist="$(mpc -f %artist% | grep -m1 '' | sed -r 's_volume: \w+.*__gm')"
title="$(mpc -f %title% | grep -m1 ''| sed -r 's_olume|epeat|andom|ingle|onsume__gm')"
  perc="$(mpc -f %name% | grep -o ' [^ ]*%' | sed -e 's/ (//' | grep -m1 '')"
printf "$(echo $artist | cut -c 1-20 ) - $(echo $title | cut -c 1-30) $perc%"

