dmenu.background       : #000000
dmenu.foreground       : #eeeeee
dmenu.sel_background   : #619D97
dmenu.sel_foreground   : #ffffff
dmenu.out_background   : #123456
dmenu.out_foreground   : #ffffff
dmenu.selhi_background : #D2493F
dmenu.selhi_foreground : #000000
dmenu.hi_background    : #000000
dmenu.hi_foreground    : #ffffff
