#!/bin/sh
# Xsetup - run as root before the login dialog appears

#   Set Keyboard speed typing
xset r rate 170 60 &

#   Set Mouse speed
xinput --set-prop 12 310 -0.75 &

#   Set Left Handed Mouse
xmodmap -e 'pointer = 3 2 1' &

#   Set keyboard to ABNT2 PT-BR
setxkbmap -model abnt2 -layout br -variant abnt2 &

#   Start unclutter to make mouse disappear after one second
unclutter --timeout 1 &
