dunst.separator.colour      : #f8f6feAA
dunst.critical.background   : #f8f6feAA
dunst.critical.foreground   : #fe2d3b
dunst.critical.frame_colour : #010000
dunst.normal.background     : #f8f6feAA
dunst.normal.foreground     : #333333
dunst.normal.frame_colour   : #9e9e9e
dunst.low.background        : #ffffffAA
dunst.low.foreground        : #444444
dunst.low.frame_colour      : #a2c0cb
